### ISSUE TITLE
Error when upgrading from 2.x to 3.0.0-rc4

### ISSUE THREAD

**Issue by stehlo** [piwik/piwik#11028]
An exception has been thrown during the rendering of a template (".form-description is undefined: failed at `.form-description;` line: 6621") in "@CoreUpdater/runUpdaterAndExit_welcome.twig" at line 8.

**Comment by Findus23** [comment]
Is it possible that this is the same issue as #10738?
Do you use the *InterSites* plugin?

**Comment by stehlo** [comment]
No, but among others I have use the following plugin from the other list:
- TreemapVisualization

**Comment by tsteur** [comment]
Can you go to Administration => Plugins. Then select the filter "Third-party" and let us know which ones are enabled?

It cannot really be triggered by TreemapVisualization but is likely a different plugin

**Comment by stehlo** [comment]
Well, I would love to, but Piwik is not working due to this error.

**Comment by mattab** [comment]
can you paste here the content of config.ini.php below the `[Plugins]` section?

Ideally we'd like to trigger our "safe mode" when this occurs, so that you can easily disable the plugin

**Comment by stehlo** [comment]
[Plugins]
CorePluginsAdmin
CoreAdminHome
CoreHome
WebsiteMeasurable
Diagnostics
CoreVisualizations
Proxy
API
Widgetize
Transitions
LanguagesManager
Actions
Dashboard
MultiSites
Referrers
UserLanguage
DevicesDetection
Goals
Ecommerce
SEO
Events
UserCountry
VisitsSummary
VisitFrequency
VisitTime
VisitorInterest
ExampleAPI
Feedback
Monolog
Login
UsersManager
SitesManager
Installation
CoreUpdater
CoreConsole
ScheduledReports
UserCountryMap
Live
CustomVariables
PrivacyManager
ImageGraph
Annotations
MobileMessaging
Overlay
SegmentEditor
Insights
Morpheus
Contents
BulkTracking
Resolution
DevicePlugins
Heartbeat
Intl
Marketplace
ProfessionalServices
UserId
CustomPiwikJs
DBStats
MobileAppMeasurable
Provider
BotTracker
ClickHeat
ComparisonDashboard
CustomAlerts
CustomDimensions
ExampleRssWidget
InterSites
PlatformsReport
QueuedTracking
SecurityInfo
TasksTimetable
TreemapVisualization
WebsiteGroups

**Comment by stehlo** [comment]
[PluginsInstalled]
Login
CoreAdminHome
UsersManager
SitesManager
Installation
CorePluginsAdmin
CoreHome
Proxy
API
Widgetize
LanguagesManager
Actions
Dashboard
MultiSites
Goals
SEO
UserCountry
VisitsSummary
VisitFrequency
VisitTime
VisitorInterest
ExampleAPI
ExamplePlugin
ExampleRssWidget
Provider
Feedback
CoreUpdater
UserCountryMap
Live
CustomVariables
PrivacyManager
ImageGraph
SegmentEditor
CoreConsole
CoreVisualizations
Referrers
ScheduledReports
Events
Morpheus
DevicesDetection
Contents
BulkTracking
Resolution
DevicePlugins
Annotations
DBStats
Insights
Transitions
Overlay
SecurityInfo
TreemapVisualization
ComparisonDashboard
BotTracker
WebsiteGroups
TasksTimetable
InterSites
QueuedTracking
Ecommerce
UserLanguage
Monolog
Diagnostics
WebsiteMeasurable
Intl
Heartbeat
UserId
ProfessionalServices
CustomPiwikJs
Marketplace
MobileAppMeasurable
ClickHeat
PlatformsReport
CustomAlerts
MobileMessaging
CustomDimensions

**Comment by sgiehl** [comment]
Maybe `ClickHeat` causes the problem. As far as I have seen that plugin is not yet compatible with Piwik 3

**Comment by tsteur** [comment]
It seems to not override the topbar event, neither does WebsiteGroups. Probably one of the others

**Comment by tsteur** [comment]
Actually InterSites is installed according to that list. Marking it as duplicate

**Comment by stehlo** [comment]
Removing InterSites doesn't help at all. I don't even know what is that plugin.

**Comment by sgiehl** [comment]
Did you also remove that plugin from filesystem?

**Comment by stehlo** [comment]
No, just disabled it via config file. Is it not a core plugin?

**Comment by stehlo** [comment]
I have moved it within the file system, and the upgrade proceeds now.
Is this plugin critical for the operation of Piwik?

**Comment by sgiehl** [comment]
No it isn't (See http://plugins.piwik.org/InterSites). Try removing it from file system.

**Comment by stehlo** [comment]
OK, thanks.
I am glad, this wasn't a production system...

**Comment by stehlo** [comment]
By the way, the version 3.0 looks very good (speedwise, etc.).

**Comment by stehlo** [comment]
Although the change of time period doesn't work. :-(
That's a regression.
And not even in my favourite Pale Moon, but in Google Chrome!

**Comment by stehlo** [comment]
OK, so it looks like this version 3.0 has still a long way to go.

Is there an easy way to downgrade back to the latest version 2?

**Comment by mattab** [comment]
Piwik 3 is ready and will be released today.

Changing time periods works for us. See it: http://demo.piwik.org/

**Comment by mattab** [comment]
there is no easy way to downgrade to 2.x

**Comment by stehlo** [comment]
Interesting, indeed.
My Piwik is nearly empty, yet it doesn't work in that way.
I wonder whether some plugins still don't need updating.
Will come back shortly.

**Comment by stehlo** [comment]
Uncaught TypeError: this.jsViewDataTable.indexOf is not a function
    at DataTable.setFixWidthToMakeEllipsisWork (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1166)
    at DataTable.bindEventsAndApplyStyle (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1142)
    at DataTable.init (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1128)
    at new DataTable (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1126)
    at HTMLDivElement.<anonymous> (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1127)
    at Function.each (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4)
    at n.fn.init.each (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4)
    at Function.DataTable.initNewDataTables (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1127)
    at HTMLDocument.eval (eval at globalEval (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4), <anonymous>:2:39)
    at i (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4)

**Comment by stehlo** [comment]
Maybe after all the insufficiency of data could be the reason...?

**Comment by mattab** [comment]
@stehlo 
* go to Settings > Plugins and update all plugins that can be updated
* go to Marketplace > Third party. Which third party plugins are listed here?
* Disable one by one the third party plugins (not those created by "piwik" since they should work), until you find that the JS error is gone

Which plugin was causing the JS error?

**Comment by stehlo** [comment]
I don't see any updateable plugins.

> Which plugin was causing the JS error?

No idea. Maybe it doesn't relate to any plugin.

**Comment by sgiehl** [comment]
You might also try to clean the `tmp` directory of Piwik.

**Comment by mattab** [comment]
Go to Marketplace > Third party. Which third party plugins are listed here?

Then, you can try to disable these plugins one by one, until you find that your Piwik date range/calendar is working well again as expected

**Comment by stehlo** [comment]
Another error:

index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4 Uncaught Error: cannot call methods on liveWidget prior to initialization; attempted to call method 'started'
    at Function.error (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:4:1813)
    at HTMLUListElement.<anonymous> (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:13:6126)
    at Function.each (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:4:2861)
    at n.fn.init.each (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:4:845)
    at n.fn.init.t.fn.(anonymous function) [as liveWidget] (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:13:5901)
    at isStarted (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:3747:26)
    at onTabBlur (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:3748:25)
    at HTMLDocument.<anonymous> (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:3750:65)
    at Object._change (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:884:509)
    at HTMLDocument.listener (https://stats.stehlik.co.uk/index.php?module=Proxy&action=getCoreJs&cb=3fb6f03e511f1dcc8401c27772117049:886:38)
error @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
(anonymous) @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:13
each @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
each @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
t.fn.(anonymous function) @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:13
isStarted @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3747
onTabBlur @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3748
(anonymous) @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3750
_change @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:884
listener @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:886

**Comment by stehlo** [comment]
By the way, just for your information, those errors do NOT relate to the changes of time periods.

They are just general errors happening when loading dashboard widgets.

**Comment by stehlo** [comment]
OK, all plugins tested (disabled and re-enabled). The only non-Piwik-produced plugin was "Bot Tracker".

This means that all the errors and time-period-change issue are not related to plugins.

**Comment by stehlo** [comment]
Now I am absolutely positive that the following error prohibits further operation of XHR responses:


Uncaught TypeError: this.jsViewDataTable.indexOf is not a function
    at DataTable.setFixWidthToMakeEllipsisWork (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1166)
    at DataTable.bindEventsAndApplyStyle (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1142)
    at DataTable.init (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1128)
    at new DataTable (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1126)
    at HTMLDivElement.<anonymous> (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1127)
    at Function.each (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4)
    at n.fn.init.each (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4)
    at Function.DataTable.initNewDataTables (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1127)
    at HTMLDocument.eval (eval at globalEval (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4), <anonymous>:2:39)
    at i (index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4)
setFixWidthToMakeEllipsisWork @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1166
bindEventsAndApplyStyle @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1142
init @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1128
DataTable @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1126
(anonymous) @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1127
each @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
each @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
DataTable.initNewDataTables @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1127
(anonymous) @ VM2877:2
i @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
add @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
n.fn.ready @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
(anonymous) @ VM2877:1
globalEval @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
ua @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:5
append @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:5
(anonymous) @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:5
K @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
html @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:5
t.fn.html @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:31
onWidgetLoadedReplaceElementWithContent @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3022
success @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1004
i @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
fireWith @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
z @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:6
(anonymous) @ index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:6

**Comment by stehlo** [comment]
I wonder whether the following is also not an issue:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

send	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:6
ajax	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:6
_buildAjaxCall	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1006
send	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:999
widgetsHelper.getAvailableWidgets	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:2721
construct	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:2750
DashboardSettingsControlBase	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3053
DashboardManagerControl	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3053
(anonymous)	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1026
each	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
each	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
UIControl.initElements	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:1026
DashboardManagerControl.initElements	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:3053
(anonymous)	@	index.php?module=CoreHome&action=index&idSite=20&period=day&date=today:619
i	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
fireWith	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
ready	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4
J	@	index.php?module=Proxy&action=getCoreJs&cb=3fb6f03…:4

**Comment by sgiehl** [comment]
You might add the following to your config.ini.php:

```
[Development]
enabled = 1
disable_merged_assets = 1
```

This enables development mode and disables the merged assets. That way all javascript files will be loaded separately. That should help to exactly trace down where the error occurs.

**Comment by stehlo** [comment]
Oops!
When I see AngularJS, I am already worried about the code...

**Comment by stehlo** [comment]
Anyway, I should mention that the problems I am describing (including the time-period-change) relate ONLY to the custom **dashboard**.

**Comment by mattab** [comment]
@stehlo can you please try to apply this patch: https://github.com/piwik/piwik/commit/0e3cf3254aa3bd202e478400aed0d4b5a4343f5a

and then deleted your tmp/ folder and try again?

**Comment by stehlo** [comment]
I just wanted to recommend something like that, because the debugging has shown that jsViewDataTable is sometimes equal to "graphEvolution", sometimes to "table", but sometimes it is not set at all.

**Comment by stehlo** [comment]
Excellent!

I have tested with other dashboard widgets and everything works fine.

Thank you, Matthieu.

The donation for the fix has been just wired to your Paypal account.

**Comment by mattab** [comment]
Thanks @stehlo for the quick feedback! it's good to know we caught this issue just before release :+1:

**Comment by stehlo** [comment]
Yes, it would have been a nasty surprise for many people.

Surprisingly, one liners can be show-stoppers sometimes... ;-)

**Comment by mattab** [comment]
as we'd like to find the root cause, do you know in which widget this error appeared? how could we reproduce this error? do you find a way now to reproduce it on demo.piwik.org (still running rc4) ?

**Comment by stehlo** [comment]
I had only 5 widgets in the following order at that time:
Column 1
- Visits Over Time
- Operating System versions
- Browsers
Column 2
- Visitors in Real-time
Column 3
- Country

The error happened regardless of the type of Measurables (Website or Mobile App).

**Comment by mattab** [comment]
fixed in #11035
