### ISSUE TITLE
Exception ".form-description is undefined: failed at" - multiple reports after Update to 3.1.1

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#12138]
Via Email:

An exception has been thrown during the rendering of a template (".form-description is undefined: failed at `.form-description;` line: 6327"). in /usr/www/users/xxxxxx/plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig 8 using PHP 5.6.31

An exception has been thrown during the rendering of a template (".form-description is undefined: failed at `.form-description;` line: 5767"). in /home/xxxxxx/html/xxxxxx/plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig 8 using PHP 7.1.2

**Comment by peterbo** [comment]
Discussed here: https://github.com/piwik/piwik/issues/10738
